In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
#popularity based, rank and popularity
#content based, based on similar content !!!!

In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')

In [ ]:
#path="/content/drive/MyDrive/dataset/myanimelist.csv"
#anime=pd.read_csv(path)

#anime.head()

In [ ]:
anime=pd.read_csv("myanimelist.csv")
anime.head()

,uid,title,synopsis,genre,aired,episodes,members,popularity,ranked,score,img_url,link
0,28891,Haikyuu!! Second Season,Following their participation at the Inter-Hig...,"['Comedy', 'Sports', 'Drama', 'School', 'Shoun...","Oct 4, 2015 to Mar 27, 2016",25.0,489888,141,25.0,8.82,https://cdn.myanimelist.net/images/anime/9/766...,https://myanimelist.net/anime/28891/Haikyuu_Se...
1,23273,Shigatsu wa Kimi no Uso,Music accompanies the path of the human metron...,"['Drama', 'Music', 'Romance', 'School', 'Shoun...","Oct 10, 2014 to Mar 20, 2015",22.0,995473,28,24.0,8.83,https://cdn.myanimelist.net/images/anime/3/671...,https://myanimelist.net/anime/23273/Shigatsu_w...
2,34599,Made in Abyss,The Abyss—a gaping chasm stretching down into ...,"['Sci-Fi', 'Adventure', 'Mystery', 'Drama', 'F...","Jul 7, 2017 to Sep 29, 2017",13.0,581663,98,23.0,8.83,https://cdn.myanimelist.net/images/anime/6/867...,https://myanimelist.net/anime/34599/Made_in_Abyss
3,5114,Fullmetal Alchemist: Brotherhood,"""In order for something to be obtained, someth...","['Action', 'Military', 'Adventure', 'Comedy', ...","Apr 5, 2009 to Jul 4, 2010",64.0,1615084,4,1.0,9.23,https://cdn.myanimelist.net/images/anime/1223/...,https://myanimelist.net/anime/5114/Fullmetal_A...
4,31758,Kizumonogatari III: Reiketsu-hen,After helping revive the legendary vampire Kis...,"['Action', 'Mystery', 'Supernatural', 'Vampire']","Jan 6, 2017",1.0,214621,502,22.0,8.83,https://cdn.myanimelist.net/images/anime/3/815...,https://myanimelist.net/anime/31758/Kizumonoga...

In [ ]:
#words_to_remove = ['[Written', 'by', 'MAL', 'Rewrite]']

In [ ]:
anime.tail()

,uid,title,synopsis,genre,aired,episodes,members,popularity,ranked,score,img_url,link
19306,32979,Flip Flappers,Cocona is an average middle schooler living wi...,"['Sci-Fi', 'Adventure', 'Comedy', 'Magic']","Oct 6, 2016 to Dec 29, 2016",13.0,134252,843,1070.0,7.73,https://cdn.myanimelist.net/images/anime/4/822...,https://myanimelist.net/anime/32979/Flip_Flappers
19307,123,Fushigi Yuugi,"While visiting the National Library, junior-hi...","['Adventure', 'Fantasy', 'Magic', 'Martial Art...","Apr 6, 1995 to Mar 28, 1996",52.0,84407,1292,1071.0,7.73,https://cdn.myanimelist.net/images/anime/2/201...,https://myanimelist.net/anime/123/Fushigi_Yuugi
19308,1281,Gakkou no Kaidan,"Years ago, all of the ghosts in a haunted scho...","['Mystery', 'Horror', 'Supernatural']","Oct 22, 2000 to Mar 25, 2001",19.0,83093,1314,1073.0,7.73,https://cdn.myanimelist.net/images/anime/9/183...,https://myanimelist.net/anime/1281/Gakkou_no_K...
19309,450,InuYasha Movie 2: Kagami no Naka no Mugenjo,Inuyasha and company have finally destroyed Na...,"['Action', 'Adventure', 'Comedy', 'Historical'...","Dec 21, 2002",1.0,71989,1469,1077.0,7.73,https://cdn.myanimelist.net/images/anime/1162/...,https://myanimelist.net/anime/450/InuYasha_Mov...
19310,87,Mobile Suit Gundam: Char's Counterattack,The year is Universal Century 0093. Char Aznab...,"['Military', 'Sci-Fi', 'Space', 'Drama', 'Mecha']","Mar 12, 1988",1.0,29248,2604,1081.0,7.73,https://cdn.myanimelist.net/images/anime/1523/...,https://myanimelist.net/anime/87/Mobile_Suit_G...

In [ ]:
anime.shape    #19311 anime, 12 column

(19311, 12)

In [ ]:
anime['episodes'].value_counts()

episodes
1.0       8807
2.0       1943
12.0      1436
13.0       825
3.0        784
          ...
3057.0       1
224.0        1
431.0        1
1565.0       1
146.0        1
Name: count, Length: 199, dtype: int64

In [ ]:
anime['genre'].value_counts()

genre
['Hentai']                                                                 1837
['Music']                                                                   728
['Comedy']                                                                  642
['Kids']                                                                    412
['Dementia']                                                                202
                                                                           ...
['Drama', 'Fantasy', 'Mystery', 'Romance', 'School']                          1
['Action', 'Comedy', 'Magic', 'Shounen', 'Super Power', 'Supernatural']       1
['Parody', 'Mecha', 'Sci-Fi']                                                 1
['Action', 'Adventure', 'Fantasy', 'Comedy', 'Super Power', 'Shounen']        1
['Music', 'Romance', 'Super Power', 'Supernatural']                           1
Name: count, Length: 4851, dtype: int64

In [ ]:
anime.columns

Index(['uid', 'title', 'synopsis', 'genre', 'aired', 'episodes', 'members',
       'popularity', 'ranked', 'score', 'img_url', 'link'],
      dtype='object')

In [ ]:
#keyrole(title, uid, genre, summary, popularity?, rank?,score? )
anime[['uid','title','synopsis','genre','episodes']]

,uid,title,synopsis,genre,episodes
0,28891,Haikyuu!! Second Season,Following their participation at the Inter-Hig...,"['Comedy', 'Sports', 'Drama', 'School', 'Shoun...",25.0
1,23273,Shigatsu wa Kimi no Uso,Music accompanies the path of the human metron...,"['Drama', 'Music', 'Romance', 'School', 'Shoun...",22.0
2,34599,Made in Abyss,The Abyss—a gaping chasm stretching down into ...,"['Sci-Fi', 'Adventure', 'Mystery', 'Drama', 'F...",13.0
3,5114,Fullmetal Alchemist: Brotherhood,"""In order for something to be obtained, someth...","['Action', 'Military', 'Adventure', 'Comedy', ...",64.0
4,31758,Kizumonogatari III: Reiketsu-hen,After helping revive the legendary vampire Kis...,"['Action', 'Mystery', 'Supernatural', 'Vampire']",1.0
...,...,...,...,...,...
19306,32979,Flip Flappers,Cocona is an average middle schooler living wi...,"['Sci-Fi', 'Adventure', 'Comedy', 'Magic']",13.0
19307,123,Fushigi Yuugi,"While visiting the National Library, junior-hi...","['Adventure', 'Fantasy', 'Magic', 'Martial Art...",52.0
19308,1281,Gakkou no Kaidan,"Years ago, all of the ghosts in a haunted scho...","['Mystery', 'Horror', 'Supernatural']",19.0
19309,450,InuYasha Movie 2: Kagami no Naka no Mugenjo,Inuyasha and company have finally destroyed Na...,"['Action', 'Adventure', 'Comedy', 'Historical'...",1.0
19310,87,Mobile Suit Gundam: Char's Counterattack,The year is Universal Century 0093. Char Aznab...,"['Military', 'Sci-Fi', 'Space', 'Drama', 'Mecha']",1.0

In [ ]:
animes=anime[['uid','title','synopsis','genre','episodes']]
animes.head()

,uid,title,synopsis,genre,episodes
0,28891,Haikyuu!! Second Season,Following their participation at the Inter-Hig...,"['Comedy', 'Sports', 'Drama', 'School', 'Shoun...",25.0
1,23273,Shigatsu wa Kimi no Uso,Music accompanies the path of the human metron...,"['Drama', 'Music', 'Romance', 'School', 'Shoun...",22.0
2,34599,Made in Abyss,The Abyss—a gaping chasm stretching down into ...,"['Sci-Fi', 'Adventure', 'Mystery', 'Drama', 'F...",13.0
3,5114,Fullmetal Alchemist: Brotherhood,"""In order for something to be obtained, someth...","['Action', 'Military', 'Adventure', 'Comedy', ...",64.0
4,31758,Kizumonogatari III: Reiketsu-hen,After helping revive the legendary vampire Kis...,"['Action', 'Mystery', 'Supernatural', 'Vampire']",1.0

In [ ]:
#preprocessing, remove brackets, check missing values}

#missing value
animes.isnull().sum()

uid           0
title         0
synopsis    975
genre         0
episodes    706
dtype: int64

In [ ]:
animes.dropna(inplace=True)

<ipython-input-23-1b0f7713d196>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  animes.dropna(inplace=True)

In [ ]:
animes.isnull().sum()

uid         0
title       0
synopsis    0
genre       0
episodes    0
dtype: int64

In [ ]:
animes.shape

(17801, 5)

In [ ]:
#duplicate check
animes.duplicated().sum()

2737

In [ ]:
animes.drop_duplicates(inplace=True)
animes.duplicated().sum()

<ipython-input-27-63a25ba621bf>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  animes.drop_duplicates(inplace=True)

0

In [ ]:
animes.shape

(15064, 5)

In [ ]:
animes.head(2)

,uid,title,synopsis,genre,episodes
0,28891,Haikyuu!! Second Season,Following their participation at the Inter-Hig...,"['Comedy', 'Sports', 'Drama', 'School', 'Shoun...",25.0
1,23273,Shigatsu wa Kimi no Uso,Music accompanies the path of the human metron...,"['Drama', 'Music', 'Romance', 'School', 'Shoun...",22.0

In [ ]:
animes.iloc[0]['genre']

"['Comedy', 'Sports', 'Drama', 'School', 'Shounen']"

In [ ]:
print(animes)

         uid                                              title  \
0      28891                            Haikyuu!! Second Season
1      23273                            Shigatsu wa Kimi no Uso
2      34599                                      Made in Abyss
3       5114                   Fullmetal Alchemist: Brotherhood
4      31758                   Kizumonogatari III: Reiketsu-hen
...      ...                                                ...
19002  10075                                        Naruto x UT
19003  35828                                   Miira no Kaikata
19004  10378                             Shinryaku!? Ika Musume
19005  33082                      Kingsglaive: Final Fantasy XV
19006  16934  Chuunibyou demo Koi ga Shitai!: Kirameki no......

                                                synopsis  \
0      Following their participation at the Inter-Hig...
1      Music accompanies the path of the human metron...
2      The Abyss—a gaping chasm stretching down into ...
3      "In order for something to be obtained, someth...
4      After helping revive the legendary vampire Kis...
...                                                  ...
19002  All-new animation offered throughout UNIQLO cl...
19003  High school student Sora Kashiwagi is accustom...
19004  After regaining her squid-like abilities, Ika ...
19005  For years, the Niflheim Empire and the kingdom...
19006  Although Yuuta Togashi and Rikka Takanashi hav...

                                                   genre  episodes
0      ['Comedy', 'Sports', 'Drama', 'School', 'Shoun...      25.0
1      ['Drama', 'Music', 'Romance', 'School', 'Shoun...      22.0
2      ['Sci-Fi', 'Adventure', 'Mystery', 'Drama', 'F...      13.0
3      ['Action', 'Military', 'Adventure', 'Comedy', ...      64.0
4       ['Action', 'Mystery', 'Supernatural', 'Vampire']       1.0
...                                                  ...       ...
19002  ['Action', 'Comedy', 'Super Power', 'Martial A...       1.0
19003        ['Slice of Life', 'Comedy', 'Supernatural']      12.0
19004             ['Slice of Life', 'Comedy', 'Shounen']      12.0
19005                                         ['Action']       1.0
19006  ['Comedy', 'Drama', 'Romance', 'School', 'Slic...       1.0

[15064 rows x 5 columns]

In [ ]:
animes.head(5)

,uid,title,synopsis,genre,episodes
0,28891,Haikyuu!! Second Season,Following their participation at the Inter-Hig...,"['Comedy', 'Sports', 'Drama', 'School', 'Shoun...",25.0
1,23273,Shigatsu wa Kimi no Uso,Music accompanies the path of the human metron...,"['Drama', 'Music', 'Romance', 'School', 'Shoun...",22.0
2,34599,Made in Abyss,The Abyss—a gaping chasm stretching down into ...,"['Sci-Fi', 'Adventure', 'Mystery', 'Drama', 'F...",13.0
3,5114,Fullmetal Alchemist: Brotherhood,"""In order for something to be obtained, someth...","['Action', 'Military', 'Adventure', 'Comedy', ...",64.0
4,31758,Kizumonogatari III: Reiketsu-hen,After helping revive the legendary vampire Kis...,"['Action', 'Mystery', 'Supernatural', 'Vampire']",1.0

In [ ]:
#seperate synopsis with comma and store in list
animes['synopsis']=animes['synopsis'].apply(lambda x:x.split())

<ipython-input-33-2769a593c613>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  animes['synopsis']=animes['synopsis'].apply(lambda x:x.split())

In [ ]:
animes.iloc[0]['synopsis']

['Following',
 'their',
 'participation',
 'at',
 'the',
 'Inter-High,',
 'the',
 'Karasuno',
 'High',
 'School',
 'volleyball',
 'team',
 'attempts',
 'to',
 'refocus',
 'their',
 'efforts,',
 'aiming',
 'to',
 'conquer',
 'the',
 'Spring',
 'tournament',
 'instead.',
 'When',
 'they',
 'receive',
 'an',
 'invitation',
 'from',
 'long-standing',
 'rival',
 'Nekoma',
 'High,',
 'Karasuno',
 'agrees',
 'to',
 'take',
 'part',
 'in',
 'a',
 'large',
 'training',
 'camp',
 'alongside',
 'many',
 'notable',
 'volleyball',
 'teams',
 'in',
 'Tokyo',
 'and',
 'even',
 'some',
 'national',
 'level',
 'players.',
 'By',
 'playing',
 'with',
 'some',
 'of',
 'the',
 'toughest',
 'teams',
 'in',
 'Japan,',
 'they',
 'hope',
 'not',
 'only',
 'to',
 'sharpen',
 'their',
 'skills,',
 'but',
 'also',
 'come',
 'up',
 'with',
 'new',
 'attacks',
 'that',
 'would',
 'strengthen',
 'them.',
 'Moreover,',
 'Hinata',
 'and',
 'Kageyama',
 'attempt',
 'to',
 'devise',
 'a',
 'more',
 'powerful',
 'weapon,',
 'one',
 'that',
 'could',
 'possibly',
 'break',
 'the',
 'sturdiest',
 'of',
 'blocks.',
 'Facing',
 'what',
 'may',
 'be',
 'their',
 'last',
 'chance',
 'at',
 'victory',
 'before',
 'the',
 'senior',
 'players',
 'graduate,',
 'the',
 'members',
 'of',
 "Karasuno's",
 'volleyball',
 'team',
 'must',
 'learn',
 'to',
 'settle',
 'their',
 'differences',
 'and',
 'train',
 'harder',
 'than',
 'ever',
 'if',
 'they',
 'hope',
 'to',
 'overcome',
 'formidable',
 'opponents',
 'old',
 'and',
 'new—including',
 'their',
 'archrival',
 'Aoba',
 'Jousai',
 'and',
 'its',
 'world-class',
 'setter',
 'Tooru',
 'Oikawa.',
 '[Written',
 'by',
 'MAL',
 'Rewrite]']

In [ ]:
animes.head()

,uid,title,synopsis,genre,episodes
0,28891,Haikyuu!! Second Season,"[Following, their, participation, at, the, Int...","['Comedy', 'Sports', 'Drama', 'School', 'Shoun...",25.0
1,23273,Shigatsu wa Kimi no Uso,"[Music, accompanies, the, path, of, the, human...","['Drama', 'Music', 'Romance', 'School', 'Shoun...",22.0
2,34599,Made in Abyss,"[The, Abyss—a, gaping, chasm, stretching, down...","['Sci-Fi', 'Adventure', 'Mystery', 'Drama', 'F...",13.0
3,5114,Fullmetal Alchemist: Brotherhood,"[""In, order, for, something, to, be, obtained,...","['Action', 'Military', 'Adventure', 'Comedy', ...",64.0
4,31758,Kizumonogatari III: Reiketsu-hen,"[After, helping, revive, the, legendary, vampi...","['Action', 'Mystery', 'Supernatural', 'Vampire']",1.0

In [ ]:
# Function to convert list to string
def list_to_string(input_list, separator=" "):
    if isinstance(input_list, list):
        return separator.join(input_list)
    return input_list  # In case it's already a string, just return it

# Convert the 'genre' and 'synopsis' columns to strings
animes['genre'] = animes['genre'].apply(list_to_string)
animes['synopsis'] = animes['synopsis'].apply(list_to_string)

# Now concatenate 'genre' and 'synopsis' columns
animes['combined'] = animes['synopsis']+ animes['genre']

# Output the result
print(animes[['genre', 'synopsis', 'combined']])

                                                   genre  \
0      ['Comedy', 'Sports', 'Drama', 'School', 'Shoun...
1      ['Drama', 'Music', 'Romance', 'School', 'Shoun...
2      ['Sci-Fi', 'Adventure', 'Mystery', 'Drama', 'F...
3      ['Action', 'Military', 'Adventure', 'Comedy', ...
4       ['Action', 'Mystery', 'Supernatural', 'Vampire']
...                                                  ...
19002  ['Action', 'Comedy', 'Super Power', 'Martial A...
19003        ['Slice of Life', 'Comedy', 'Supernatural']
19004             ['Slice of Life', 'Comedy', 'Shounen']
19005                                         ['Action']
19006  ['Comedy', 'Drama', 'Romance', 'School', 'Slic...

                                                synopsis  \
0      Following their participation at the Inter-Hig...
1      Music accompanies the path of the human metron...
2      The Abyss—a gaping chasm stretching down into ...
3      "In order for something to be obtained, someth...
4      After helping revive the legendary vampire Kis...
...                                                  ...
19002  All-new animation offered throughout UNIQLO cl...
19003  High school student Sora Kashiwagi is accustom...
19004  After regaining her squid-like abilities, Ika ...
19005  For years, the Niflheim Empire and the kingdom...
19006  Although Yuuta Togashi and Rikka Takanashi hav...

                                                combined
0      Following their participation at the Inter-Hig...
1      Music accompanies the path of the human metron...
2      The Abyss—a gaping chasm stretching down into ...
3      "In order for something to be obtained, someth...
4      After helping revive the legendary vampire Kis...
...                                                  ...
19002  All-new animation offered throughout UNIQLO cl...
19003  High school student Sora Kashiwagi is accustom...
19004  After regaining her squid-like abilities, Ika ...
19005  For years, the Niflheim Empire and the kingdom...
19006  Although Yuuta Togashi and Rikka Takanashi hav...

[15064 rows x 3 columns]

<ipython-input-36-fb24d833050c>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  animes['genre'] = animes['genre'].apply(list_to_string)
<ipython-input-36-fb24d833050c>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  animes['synopsis'] = animes['synopsis'].apply(list_to_string)
<ipython-input-36-fb24d833050c>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  animes['combined'] = animes['synopsis']+ animes['genre']

In [ ]:
animes.head()

,uid,title,synopsis,genre,episodes,combined
0,28891,Haikyuu!! Second Season,Following their participation at the Inter-Hig...,"['Comedy', 'Sports', 'Drama', 'School', 'Shoun...",25.0,Following their participation at the Inter-Hig...
1,23273,Shigatsu wa Kimi no Uso,Music accompanies the path of the human metron...,"['Drama', 'Music', 'Romance', 'School', 'Shoun...",22.0,Music accompanies the path of the human metron...
2,34599,Made in Abyss,The Abyss—a gaping chasm stretching down into ...,"['Sci-Fi', 'Adventure', 'Mystery', 'Drama', 'F...",13.0,The Abyss—a gaping chasm stretching down into ...
3,5114,Fullmetal Alchemist: Brotherhood,"""In order for something to be obtained, someth...","['Action', 'Military', 'Adventure', 'Comedy', ...",64.0,"""In order for something to be obtained, someth..."
4,31758,Kizumonogatari III: Reiketsu-hen,After helping revive the legendary vampire Kis...,"['Action', 'Mystery', 'Supernatural', 'Vampire']",1.0,After helping revive the legendary vampire Kis...

In [ ]:
animes.iloc[0]['combined']

"Following their participation at the Inter-High, the Karasuno High School volleyball team attempts to refocus their efforts, aiming to conquer the Spring tournament instead. When they receive an invitation from long-standing rival Nekoma High, Karasuno agrees to take part in a large training camp alongside many notable volleyball teams in Tokyo and even some national level players. By playing with some of the toughest teams in Japan, they hope not only to sharpen their skills, but also come up with new attacks that would strengthen them. Moreover, Hinata and Kageyama attempt to devise a more powerful weapon, one that could possibly break the sturdiest of blocks. Facing what may be their last chance at victory before the senior players graduate, the members of Karasuno's volleyball team must learn to settle their differences and train harder than ever if they hope to overcome formidable opponents old and new—including their archrival Aoba Jousai and its world-class setter Tooru Oikawa. [Written by MAL Rewrite]['Comedy', 'Sports', 'Drama', 'School', 'Shounen']"

In [ ]:
import re
def remove_brackets(text):
    return re.sub(r'\[|\]', '', text)

# Apply this function to the 'combined' column
animes['combined'] = animes['combined'].apply(remove_brackets)

animes.head()

<ipython-input-39-f6aa3b0bde28>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  animes['combined'] = animes['combined'].apply(remove_brackets)

,uid,title,synopsis,genre,episodes,combined
0,28891,Haikyuu!! Second Season,Following their participation at the Inter-Hig...,"['Comedy', 'Sports', 'Drama', 'School', 'Shoun...",25.0,Following their participation at the Inter-Hig...
1,23273,Shigatsu wa Kimi no Uso,Music accompanies the path of the human metron...,"['Drama', 'Music', 'Romance', 'School', 'Shoun...",22.0,Music accompanies the path of the human metron...
2,34599,Made in Abyss,The Abyss—a gaping chasm stretching down into ...,"['Sci-Fi', 'Adventure', 'Mystery', 'Drama', 'F...",13.0,The Abyss—a gaping chasm stretching down into ...
3,5114,Fullmetal Alchemist: Brotherhood,"""In order for something to be obtained, someth...","['Action', 'Military', 'Adventure', 'Comedy', ...",64.0,"""In order for something to be obtained, someth..."
4,31758,Kizumonogatari III: Reiketsu-hen,After helping revive the legendary vampire Kis...,"['Action', 'Mystery', 'Supernatural', 'Vampire']",1.0,After helping revive the legendary vampire Kis...

In [ ]:
# Define a function to clean the 'combined' column
def clean_combined_column(text):
    # Add space after "MAL" and remove commas and single quotes
    text = re.sub(r"Written by MAL Rewrite", "Written by MAL Rewrite ", text)
    text = text.replace("'", "")  # Remove single quotes
    text = text.replace(",", "")  # Remove commas
    return text

# Apply this function to the 'combined' column
animes['combined'] = animes['combined'].apply(clean_combined_column)

<ipython-input-40-a981b6931b85>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  animes['combined'] = animes['combined'].apply(clean_combined_column)

In [ ]:
animes.head()

,uid,title,synopsis,genre,episodes,combined
0,28891,Haikyuu!! Second Season,Following their participation at the Inter-Hig...,"['Comedy', 'Sports', 'Drama', 'School', 'Shoun...",25.0,Following their participation at the Inter-Hig...
1,23273,Shigatsu wa Kimi no Uso,Music accompanies the path of the human metron...,"['Drama', 'Music', 'Romance', 'School', 'Shoun...",22.0,Music accompanies the path of the human metron...
2,34599,Made in Abyss,The Abyss—a gaping chasm stretching down into ...,"['Sci-Fi', 'Adventure', 'Mystery', 'Drama', 'F...",13.0,The Abyss—a gaping chasm stretching down into ...
3,5114,Fullmetal Alchemist: Brotherhood,"""In order for something to be obtained, someth...","['Action', 'Military', 'Adventure', 'Comedy', ...",64.0,"""In order for something to be obtained somethi..."
4,31758,Kizumonogatari III: Reiketsu-hen,After helping revive the legendary vampire Kis...,"['Action', 'Mystery', 'Supernatural', 'Vampire']",1.0,After helping revive the legendary vampire Kis...

In [ ]:
new_animes=animes[['uid','title','combined']]
new_animes.head()
new_animes.iloc[0]['combined']

'Following their participation at the Inter-High the Karasuno High School volleyball team attempts to refocus their efforts aiming to conquer the Spring tournament instead. When they receive an invitation from long-standing rival Nekoma High Karasuno agrees to take part in a large training camp alongside many notable volleyball teams in Tokyo and even some national level players. By playing with some of the toughest teams in Japan they hope not only to sharpen their skills but also come up with new attacks that would strengthen them. Moreover Hinata and Kageyama attempt to devise a more powerful weapon one that could possibly break the sturdiest of blocks. Facing what may be their last chance at victory before the senior players graduate the members of Karasunos volleyball team must learn to settle their differences and train harder than ever if they hope to overcome formidable opponents old and new—including their archrival Aoba Jousai and its world-class setter Tooru Oikawa. Written by MAL Rewrite Comedy Sports Drama School Shounen'

In [ ]:
new_animes['combined']=new_animes['combined'].apply(lambda x:x.lower())

new_animes.iloc[0]['combined']

<ipython-input-43-907e7b7a00da>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_animes['combined']=new_animes['combined'].apply(lambda x:x.lower())

'following their participation at the inter-high the karasuno high school volleyball team attempts to refocus their efforts aiming to conquer the spring tournament instead. when they receive an invitation from long-standing rival nekoma high karasuno agrees to take part in a large training camp alongside many notable volleyball teams in tokyo and even some national level players. by playing with some of the toughest teams in japan they hope not only to sharpen their skills but also come up with new attacks that would strengthen them. moreover hinata and kageyama attempt to devise a more powerful weapon one that could possibly break the sturdiest of blocks. facing what may be their last chance at victory before the senior players graduate the members of karasunos volleyball team must learn to settle their differences and train harder than ever if they hope to overcome formidable opponents old and new—including their archrival aoba jousai and its world-class setter tooru oikawa. written by mal rewrite comedy sports drama school shounen'

In [ ]:
#recommendation

#transformation
import nltk
from nltk.stem import PorterStemmer
ps=PorterStemmer()

In [ ]:
def stems(text):
  l=[]
  for i in text.split():
    l.append(ps.stem(i))
  return " ".join(l)

In [ ]:
new_animes['combined']=new_animes['combined'].apply(stems) #stemimg:the process of reducing words to their base or root form

new_animes.iloc[0]['combined']

<ipython-input-46-663a4d5e0b9a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_animes['combined']=new_animes['combined'].apply(stems) #stemimg:the process of reducing words to their base or root form

'follow their particip at the inter-high the karasuno high school volleybal team attempt to refocu their effort aim to conquer the spring tournament instead. when they receiv an invit from long-stand rival nekoma high karasuno agre to take part in a larg train camp alongsid mani notabl volleybal team in tokyo and even some nation level players. by play with some of the toughest team in japan they hope not onli to sharpen their skill but also come up with new attack that would strengthen them. moreov hinata and kageyama attempt to devis a more power weapon one that could possibl break the sturdiest of blocks. face what may be their last chanc at victori befor the senior player graduat the member of karasuno volleybal team must learn to settl their differ and train harder than ever if they hope to overcom formid oppon old and new—includ their archriv aoba jousai and it world-class setter tooru oikawa. written by mal rewrit comedi sport drama school shounen'

In [ ]:
new_animes.head()

,uid,title,combined
0,28891,Haikyuu!! Second Season,follow their particip at the inter-high the ka...
1,23273,Shigatsu wa Kimi no Uso,music accompani the path of the human metronom...
2,34599,Made in Abyss,the abyss—a gape chasm stretch down into the d...
3,5114,Fullmetal Alchemist: Brotherhood,"""in order for someth to be obtain someth of eq..."
4,31758,Kizumonogatari III: Reiketsu-hen,after help reviv the legendari vampir kiss-sho...

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')           #most frequent words and stop_words will get rid of unnecessary words??

In [ ]:
vector=cv.fit_transform(new_animes['combined']).toarray()
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
vector.shape    #rows,columns

(15064, 5000)

In [ ]:
#to measure the cosine similarity
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity=cosine_similarity(vector)

In [ ]:
similarity

array([[1.        , 0.1136249 , 0.08333623, ..., 0.09467621, 0.0579771 ,
        0.07595004],
       [0.1136249 , 1.        , 0.14735331, ..., 0.09847319, 0.27889799,
        0.07021868],
       [0.08333623, 0.14735331, 1.        , ..., 0.08215419, 0.1365529 ,
        0.09205746],
       ...,
       [0.09467621, 0.09847319, 0.08215419, ..., 1.        , 0.06123724,
        0.13073024],
       [0.0579771 , 0.27889799, 0.1365529 , ..., 0.06123724, 1.        ,
        0.02911113],
       [0.07595004, 0.07021868, 0.09205746, ..., 0.13073024, 0.02911113,
        1.        ]])

In [ ]:
similarity.shape

(15064, 15064)

In [ ]:
list(enumerate(similarity[0]))

[(0, 1.0),
 (1, 0.11362490392942798),
 (2, 0.08333622700256466),
 (3, 0.09359995293260694),
 (4, 0.05762250021698473),
 (5, 0.06960093862470138),
 (6, 0.08291849892341732),
 (7, 0.04054794588182809),
 (8, 0.13339922576796254),
 (9, 0.13419091951824633),
 (10, 0.4372631476231092),
 (11, 0.06353667351380256),
 (12, 0.08678652919404432),
 (13, 0.06801889244184443),
 (14, 0.16583699784683462),
 (15, 0.0843889368629713),
 (16, 0.1030833932224501),
 (17, 0.04899959575500253),
 (18, 0.1012131297760109),
 (19, 0.08765314158255662),
 (20, 0.038509039453410415),
 (21, 0.05734345499245157),
 (22, 0.04011426554254583),
 (23, 0.033107259176155104),
 (24, 0.04446640858932085),
 (25, 0.060012003601200424),
 (26, 0.15184862096601529),
 (27, 0.15983788754422587),
 (28, 0.056579859598667105),
 (29, 0.1944611170656493),
 (30, 0.06174654780291236),
 (31, 0.09723055853282467),
 (32, 0.10515252921688406),
 (33, 0.05256920691801377),
 (34, 0.09703028940457657),
 (35, 0.06351073488299556),
 (36, 0.06585756417049701),
 (37, 0.06919509878818318),
 (38, 0.10394383930128556),
 (39, 0.0692958928675237),
 (40, 0.08696565534786727),
 (41, 0.03989418139519557),
 (42, 0.11000381964338536),
 (43, 0.11227217828476799),
 (44, 0.10515252921688406),
 (45, 0.021030505843376807),
 (46, 0.0733358797622569),
 (47, 0.10033640064279385),
 (48, 0.0454809819108882),
 (49, 0.13750477455423168),
 (50, 0.19599838302001013),
 (51, 0.07531446678801507),
 (52, 0.10585122480499264),
 (53, 0.13518424387270375),
 (54, 0.1191586461884342),
 (55, 0.09166984970282113),
 (56, 0.131707777961327),
 (57, 0.08199200616907877),
 (58, 0.08745286171094284),
 (59, 0.10041928905068676),
 (60, 0.07938841860374446),
 (61, 0.0734993936325038),
 (62, 0.08652532008633532),
 (63, 0.10456292660552613),
 (64, 0.026462806201248162),
 (65, 0.07669649888473705),
 (66, 0.10041928905068676),
 (67, 0.03901727911659971),
 (68, 0.08333622700256466),
 (69, 0.1521898968587677),
 (70, 0.03132753523013991),
 (71, 0.061113233135214086),
 (72, 0.037424059428255996),
 (73, 0.0),
 (74, 0.040492965590937416),
 (75, 0.10134483201751004),
 (76, 0.01709651512370952),
 (77, 0.09965563318429557),
 (78, 0.02283829997007301),
 (79, 0.07817631049941043),
 (80, 0.030556616567607043),
 (81, 0.07247137945655606),
 (82, 0.03241018617760822),
 (83, 0.2078876786025711),
 (84, 0.09362465057662687),
 (85, 0.14969623771302398),
 (86, 0.052233744580509334),
 (87, 0.06290028928221465),
 (88, 0.028988551782622423),
 (89, 0.12618303506026085),
 (90, 0.041327959945780576),
 (91, 0.057977103565244846),
 (92, 0.1282238634278214),
 (93, 0.0452112913727343),
 (94, 0.08615072188288476),
 (95, 0.10213598244722932),
 (96, 0.07719994003110989),
 (97, 0.07023110240987948),
 (98, 0.049331051139854976),
 (99, 0.13231403100624078),
 (100, 0.08585668058148864),
 (101, 0.08291849892341731),
 (102, 0.06311747577748679),
 (103, 0.045834924851410566),
 (104, 0.061113233135214086),
 (105, 0.19847750074739184),
 (106, 0.027639499641139105),
 (107, 0.015495032701332583),
 (108, 0.11128297681493146),
 (109, 0.11212924738240747),
 (110, 0.09794139192284194),
 (111, 0.07874033903918981),
 (112, 0.05001000300100035),
 (113, 0.19026059766179765),
 (114, 0.09840667431338067),
 (115, 0.05347407899331233),
 (116, 0.08589855167911616),
 (117, 0.24698619121164944),
 (118, 0.046948486159466916),
 (119, 0.07459986570544265),
 (120, 0.1205916410190244),
 (121, 0.11414492908992477),
 (122, 0.008585668058148864),
 (123, 0.12645498157195398),
 (124, 0.1191586461884342),
 (125, 0.05967198951293042),
 (126, 0.05537229723774713),
 (127, 0.03666793988112845),
 (128, 0.08291849892341732),
 (129, 0.0739371544634788),
 (130, 0.160422236979937),
 (131, 0.02366905341655754),
 (132, 0.18428232618152637),
 (133, 0.11883734931789684),
 (134, 0.09716984634549204),
 (135, 0.0741645600740017),
 (136, 0.09243697478991597),
 (137, 0.06407385564708999),
 (138, 0.037424059428255996),
 (139, 0.036110522895793015),
 (140, 0.09716984634549204),
 (141, 0.014144964899666776),
 (142, 0.11896650634908043),
 (143, 0.0737928055521709),
 (144, 0.06736330697086078),
 (145, 0.09872137660303817),
 (146, 0.07484811885651199),
 (147, 0.06779904482412286),
 (148, 0.1833396994056423),
 (149, 0.024597601850723634),
 (150, 0.17044535971465843),
 (151, 0.026191385629377464),
 (152, 0.0392870784440662),
 (153, 0.06507507028079611),
 (154, 0.04944304004933447),
 (155, 0.10536454992916135),
 (156, 0.18541140018500424),
 (157, 0.145845837799237),
 (158, 0.024499797877501263),
 (159, 0.24597601850723633),
 (160, 0.0838771261337098),
 (161, 0.06960093862470138),
 (162, 0.03580319370775825),
 (163, 0.16824404674701443),
 (164, 0.07001400420140048),
 (165, 0.04145924946170866),
 (166, 0.07831883807534978),
 (167, 0.048999595755002526),
 (168, 0.06482037235521645),
 (169, 0.11799667938277618),
 (170, 0.10134483201751004),
 (171, 0.14260481918147616),
 (172, 0.10803395392536075),
 (173, 0.13371421847515277),
 (174, 0.023474243079733458),
 (175, 0.04702564066699709),
 (176, 0.11491423807712053),
 (177, 0.07001400420140048),
 (178, 0.0712987719910831),
 (179, 0.10242470664851559),
 (180, 0.058968236959854745),
 (181, 0.22306219940452582),
 (182, 0.12206232513855217),
 (183, 0.11055799856455642),
 (184, 0.0),
 (185, 0.09799919151000505),
 (186, 0.12884782751867424),
 (187, 0.060281721830312406),
 (188, 0.12986562041232994),
 (189, 0.14379694838044402),
 (190, 0.11531533611365358),
 (191, 0.12002400720240083),
 (192, 0.056579859598667105),
 (193, 0.1385917857350474),
 (194, 0.06482037235521644),
 (195, 0.2644989436529957),
 (196, 0.05833535890179525),
 (197, 0.09538540869851267),
 (198, 0.07129877199108309),
 (199, 0.11917080461366747),
 (200, 0.10169856723618428),
 (201, 0.050616206988671766),
 (202, 0.23512820333498546),
 (203, 0.10412001542652122),
 (204, 0.04054794588182809),
 (205, 0.09263992803733187),
 (206, 0.03528374160166421),
 (207, 0.15797289868880232),
 (208, 0.076924423603812),
 (209, 0.049425070562987984),
 (210, 0.037775466756813224),
 (211, 0.13890079790403523),
 (212, 0.07160279695308712),
 (213, 0.038509039453410415),
 (214, 0.08810155151474873),
 (215, 0.11967560586596665),
 (216, 0.09799919151000505),
 (217, 0.06898859249362539),
 (218, 0.028988551782622423),
 (219, 0.0),
 (220, 0.10041928905068676),
 (221, 0.05863223287455782),
 (222, 0.08412202337350723),
 (223, 0.05189783277099558),
 (224, 0.09166984970282115),
 (225, 0.0),
 (226, 0.07180952651135203),
 (227, 0.03241018617760822),
 (228, 0.09723055853282467),
 (229, 0.14108976995165778),
 (230, 0.05527899928227821),
 (231, 0.02075913310839823),
 (232, 0.07938841860374449),
 (233, 0.0936414698798393),
 (234, 0.2277627459827864),
 (235, 0.03872051297887277),
 (236, 0.1223652811547686),
 (237, 0.10257909074225713),
 (238, 0.08761611807865254),
 (239, 0.049425070562987984),
 (240, 0.07866339502806552),
 (241, 0.02518364450454215),
 (242, 0.059310084675585587),
 (243, 0.017641870800832106),
 (244, 0.12019935281408409),
 (245, 0.188884697279275),
 (246, 0.07817631049941043),
 (247, 0.030556616567607043),
 (248, 0.12360760012333617),
 (249, 0.04446640858932085),
 (250, 0.047873017674234686),
 (251, 0.1375047745542317),
 (252, 0.24325638628366397),
 (253, 0.0864271631402886),
 (254, 0.15000520860461639),
 (255, 0.06456864180286605),
 (256, 0.019114484997483857),
 (257, 0.032928782085248506),
 (258, 0.05500190982169268),
 (259, 0.05472894580516029),
 (260, 0.2149848538733787),
 (261, 0.07484811885651198),
 (262, 0.3323314274501713),
 (263, 0.15894111747616887),
 (264, 0.0),
 (265, 0.044797018409678674),
 (266, 0.07978836279039114),
 (267, 0.04513511391108638),
 (268, 0.060099676407042044),
 (269, 0.09060388497415424),
 (270, 0.05969697778434098),
 (271, 0.0661570155031204),
 (272, 0.028632850559705388),
 (273, 0.15093109823994444),
 (274, 0.05694068649569659),
 (275, 0.07802988536525109),
 (276, 0.11705183734979913),
 (277, 0.06585756417049701),
 (278, 0.09104196663054404),
 (279, 0.11934397902586084),
 (280, 0.04842648135214954),
 (281, 0.0692958928675237),
 (282, 0.18003601080360127),
 (283, 0.11802058809766561),
 (284, 0.039088155249705214),
 (285, 0.11227217828476799),
 (286, 0.189666268553372),
 (287, 0.11212924738240747),
 (288, 0.09723055853282467),
 (289, 0.0762739254271382),
 (290, 0.11055799856455642),
 (291, 0.08509520756235604),
 (292, 0.0634637421019531),
 (293, 0.10786761979449293),
 (294, 0.0),
 (295, 0.08129248815339898),
 (296, 0.04348282767393363),
 (297, 0.0737928055521709),
 (298, 0.08583315498012044),
 (299, 0.08468097984399409),
 (300, 0.13812794737179585),
 (301, 0.048239866086317626),
 (302, 0.13846973217924022),
 (303, 0.07781621503131148),
 (304, 0.06669961288398127),
 (305, 0.03492624766303998),
 (306, 0.05779676999133413),
 (307, 0.09590763214758384),
 (308, 0.15070430457578102),
 (309, 0.16466586148432635),
 (310, 0.1366533436151313),
 (311, 0.0),
 (312, 0.07086268978414048),
 (313, 0.1537350115670227),
 (314, 0.12164383764548428),
 (315, 0.10725701313848277),
 (316, 0.31755367441497795),
 (317, 0.09166984970282113),
 (318, 0.12222646627042819),
 (319, 0.06585756417049701),
 (320, 0.017724117730609792),
 (321, 0.1093929250055606),
 (322, 0.12126781251816647),
 (323, 0.11055799856455642),
 (324, 0.12806290809781326),
 (325, 0.16577473503335913),
 (326, 0.0),
 (327, 0.17690471087956422),
 (328, 0.1034564094673936),
 (329, 0.07156849040973139),
 (330, 0.07484811885651198),
 (331, 0.09538540869851267),
 (332, 0.10446748916101867),
 (333, 0.38892223413129867),
 (334, 0.07595004317667418),
 (335, 0.09231315478616015),
 (336, 0.140444140102969),
 (337, 0.023474243079733458),
 (338, 0.08001600480160057),
 (339, 0.08896512701337837),
 (340, 0.15547175415278727),
 (341, 0.0889328171786417),
 (342, 0.05765766805682678),
 (343, 0.08204056525309218),
 (344, 0.08878188247894082),
 (345, 0.1113556553750779),
 (346, 0.022233204294660427),
 (347, 0.11803342130469507),
 (348, 0.08893281717864168),
 (349, 0.09166984970282115),
 (350, 0.09261982170436857),
 (351, 0.06384263348065998),
 (352, 0.09730255451346558),
 (353, 0.09723055853282465),
 (354, 0.08102546544402055),
 (355, 0.053485687390061105),
 (356, 0.11346027674980808),
 (357, 0.09634388527686186),
 (358, 0.02931611643727891),
 (359, 0.04011426554254583),
 (360, 0.03705534049110071),
 (361, 0.09703028940457657),
 (362, 0.03813696271356911),
 (363, 0.04702564066699709),
 (364, 0.09828039493309124),
 (365, 0.08333622700256464),
 (366, 0.04291657749006022),
 (367, 0.10879209623669536),
 (368, 0.13358437398443224),
 (369, 0.09794139192284196),
 (370, 0.08039977681052937),
 (371, 0.045834924851410566),
 (372, 0.19095702614550147),
 (373, 0.056430768800396505),
 (374, 0.11441088814070734),
 (375, 0.061113233135214086),
 (376, 0.1000200060020007),
 (377, 0.10878756313824399),
 (378, 0.11112063832322817),
 (379, 0.08988968316207743),
 (380, 0.10459211700463349),
 (381, 0.07660198683542199),
 (382, 0.08988968316207743),
 (383, 0.08623574061703175),
 (384, 0.10394383930128556),
 (385, 0.06149400462680908),
 (386, 0.1000200060020007),
 (387, 0.06585756417049701),
 (388, 0.19082600930253335),
 (389, 0.04149699116225229),
 (390, 0.042949275839558085),
 (391, 0.07484811885651199),
 (392, 0.06813921830810515),
 (393, 0.0452112913727343),
 (394, 0.09896596653698304),
 (395, 0.019544077624852607),
 (396, 0.11419149985036504),
 (397, 0.019544077624852607),
 (398, 0.156701233741528),
 (399, 0.20075597946407323),
 (400, 0.12126781251816647),
 (401, 0.15121603543570378),
 (402, 0.1140686472060285),
 (403, 0.11595420713048969),
 (404, 0.058823529411764705),
 (405, 0.08001600480160057),
 (406, 0.08896512701337837),
 (407, 0.1385917857350474),
 (408, 0.08462039188731345),
 (409, 0.052925612402496325),
 (410, 0.07156849040973137),
 (411, 0.15254785085427644),
 (412, 0.11764705882352941),
 (413, 0.028988551782622423),
 (414, 0.1893404969901789),
 (415, 0.08710975760966162),
 (416, 0.1921922268560893),
 (417, 0.057265701119410775),
 (418, 0.07339461896251281),
 (419, 0.1668725042981118),
 (420, 0.14494275891311212),
 (421, 0.12073003686384444),
 (422, 0.0),
 (423, 0.05863223287455782),
 (424, 0.028988551782622423),
 (425, 0.11002200660220077),
 (426, 0.15449391857857342),
 (427, 0.11119157394380932),
 (428, 0.09887865147828517),
 (429, 0.1453139317587876),
 (430, 0.05641889238885797),
 (431, 0.040742155423476055),
 (432, 0.32620546571572073),
 (433, 0.07531446678801507),
 (434, 0.04630026596801174),
 (435, 0.05442734619235176),
 (436, 0.35829704776705745),
 (437, 0.053933809897246464),
 (438, 0.05809578762715321),
 (439, 0.0820598522759869),
 (440, 0.1323703228747761),
 (441, 0.052925612402496325),
 (442, 0.028988551782622423),
 (443, 0.13241200512629717),
 (444, 0.11857708957152227),
 (445, 0.08696565534786727),
 (446, 0.06522424151090045),
 (447, 0.06001200360120042),
 (448, 0.06559360493526302),
 (449, 0.05031036607998148),
 (450, 0.0532820178597688),
 (451, 0.16682720405450543),
 (452, 0.06049403547011902),
 (453, 0.1778656343572834),
 (454, 0.2130214807490179),
 (455, 0.09565734053059191),
 (456, 0.07938841860374449),
 (457, 0.07484811885651199),
 (458, 0.12500434050384698),
 (459, 0.0733358797622569),
 (460, 0.14625448482542613),
 (461, 0.05762536864918489),
 (462, 0.10394383930128555),
 (463, 0.08779260569872764),
 (464, 0.08642716314028862),
 (465, 0.10186058512962583),
 (466, 0.1891004612496801),
 (467, 0.07296297284752787),
 (468, 0.09205101496312952),
 (469, 0.12898433165864914),
 (470, 0.07959171834405435),
 (471, 0.03528374160166421),
 (472, 0.10512966748616122),
 (473, 0.06515364124789427),
 (474, 0.10703048914430414),
 (475, 0.0),
 (476, 0.10041928905068676),
 (477, 0.14594385548042743),
 (478, 0.06868534446519091),
 (479, 0.07265696587939381),
 (480, 0.04656833021738664),
 (481, 0.10585122480499262),
 (482, 0.10656403571953761),
 (483, 0.057394404318355144),
 (484, 0.04989874590434132),
 (485, 0.08951983884653117),
 (486, 0.07645793998993543),
 (487, 0.15993762327260574),
 (488, 0.07795787947596416),
 (489, 0.37424059428255996),
 (490, 0.1260269531002754),
 (491, 0.06262242910851497),
 (492, 0.08354078531810259),
 (493, 0.046780074285319995),
 (494, 0.11595420713048969),
 (495, 0.04011426554254583),
 (496, 0.10879209623669536),
 (497, 0.0),
 (498, 0.06340936093987057),
 (499, 0.0503672890090843),
 (500, 0.030556616567607043),
 (501, 0.12618303506026085),
 (502, 0.0593241642211075),
 (503, 0.06621451835231021),
 (504, 0.1892745525903913),
 (505, 0.0),
 (506, 0.09405128133399418),
 (507, 0.07645793998993543),
 (508, 0.12964074471043288),
 (509, 0.10275246654751795),
 (510, 0.07781621503131149),
 (511, 0.02567269296894028),
 (512, 0.15278308283803518),
 (513, 0.14494275891311212),
 (514, 0.03505084307229468),
 (515, 0.022917462425705283),
 (516, 0.194094554784834),
 (517, 0.14173974484034102),
 (518, 0.13015014056159221),
 (519, 0.1016985672361843),
 (520, 0.079190688736056),
 (521, 0.0452112913727343),
 (522, 0.17533228592659694),
 (523, 0.11848200342774015),
 (524, 0.20484941329703119),
 (525, 0.08525122857563007),
 (526, 0.11726446574911564),
 (527, 0.11441088814070732),
 (528, 0.07803455823319942),
 (529, 0.09260053193602348),
 (530, 0.1385332464353989),
 (531, 0.07093625942295553),
 (532, 0.17487324928060657),
 (533, 0.06385043677268701),
 (534, 0.1936879087666573),
 (535, 0.06009967640704205),
 (536, 0.07160638741551652),
 (537, 0.1134120265767778),
 (538, 0.025424641809046074),
 (539, 0.18115886072321397),
 (540, 0.03782009224993602),
 (541, 0.12059966521579407),
 (542, 0.14725377234348785),
 (543, 0.22300530925746784),
 (544, 0.3805472489613685),
 (545, 0.09673824874398687),
 (546, 0.07604576480401899),
 (547, 0.05366072556077453),
 (548, 0.0626804934966112),
 (549, 0.17166630996024085),
 (550, 0.09467621366623016),
 (551, 0.10533310507722671),
 (552, 0.15000520860461639),
 (553, 0.07225998946968801),
 (554, 0.024499797877501263),
 (555, 0.0965841707683979),
 (556, 0.0737928055521709),
 (557, 0.10694815798662466),
 (558, 0.027639499641139105),
 (559, 0.08780379160763443),
 (560, 0.103754953375082),
 (561, 0.0739371544634788),
 (562, 0.04461243988090516),
 (563, 0.3218514483005924),
 (564, 0.11227217828476797),
 (565, 0.12349309560582472),
 (566, 0.24112688732124965),
 (567, 0.11119157394380932),
 (568, 0.1469987872650076),
 (569, 0.043067342296025546),
 (570, 0.06563575500333635),
 (571, 0.12925888601730254),
 (572, 0.12396026161066069),
 (573, 0.12768526696131996),
 (574, 0.09330402204403158),
 (575, 0.1796454381871961),
 (576, 0.14469264180024155),
 (577, 0.0699230178027249),
 (578, 0.12598815766974242),
 (579, 0.02131280714390752),
 (580, 0.10213598244722932),
 (581, 0.07938841860374449),
 (582, 0.30295571856695414),
 (583, 0.10218812190769166),
 (584, 0.04234048992199704),
 (585, 0.04438655265790939),
 (586, 0.10451970985368819),
 (587, 0.17614708551003075),
 (588, 0.09565734053059191),
 (589, 0.10294789535687282),
 (590, 0.021030505843376807),
 (591, 0.09391975123591795),
 (592, 0.048999595755002526),
 (593, 0.040996003084539386),
 (594, 0.0881427557658975),
 (595, 0.16398401233815754),
 (596, 0.09485931467873493),
 (597, 0.02366905341655754),
 (598, 0.057977103565244846),
 (599, 0.08412202337350723),
 (600, 0.06997801653302367),
 (601, 0.11112734830411189),
 (602, 0.07334800440146717),
 (603, 0.1088546923847035),
 (604, 0.13527990831890463),
 (605, 0.040199888405264686),
 (606, 0.06385043677268701),
 (607, 0.22917462425705282),
 (608, 0.14773136823638333),
 (609, 0.019544077624852607),
 (610, 0.10294789535687282),
 (611, 0.3977196492840078),
 (612, 0.14285714285714285),
 (613, 0.1426878473488945),
 (614, 0.09362465057662687),
 (615, 0.01866886465152995),
 (616, 0.07339461896251281),
 (617, 0.09362465057662687),
 (618, 0.0641688947919748),
 (619, 0.13853324643539888),
 (620, 0.04648509810399775),
 (621, 0.08574929257125441),
 (622, 0.10073457801816858),
 (623, 0.10745269585902952),
 (624, 0.07222104579158603),
 (625, 0.028289929799333553),
 (626, 0.04842648135214954),
 (627, 0.11705183734979913),
 (628, 0.0712716198624504),
 (629, 0.11417523209619027),
 (630, 0.09658417076839787),
 (631, 0.0788968447218585),
 (632, 0.0734993936325038),
 (633, 0.40996003084539384),
 (634, 0.06997801653302368),
 (635, 0.09313666043477328),
 (636, 0.15748067807837962),
 (637, 0.07363099515889293),
 (638, 0.15522433311065714),
 (639, 0.10488452670408736),
 (640, 0.10107935721436755),
 (641, 0.06171114063915285),
 (642, 0.08696565534786727),
 (643, 0.1852396434087371),
 (644, 0.16606716728147164),
 (645, 0.1436027354571202),
 (646, 0.17533228592659691),
 (647, 0.052925612402496304),
 (648, 0.14725377234348788),
 (649, 0.3100620186062022),
 (650, 0.09032498683710999),
 (651, 0.10256589813841603),
 (652, 0.06809065496481954),
 (653, 0.12465268062907156),
 (654, 0.10515252921688405),
 (655, 0.0962947277221147),
 (656, 0.28872786546283785),
 (657, 0.02917144666814949),
 (658, 0.10041928905068676),
 (659, 0.10928568076913749),
 (660, 0.10735273561459707),
 (661, 0.32017320917219316),
 (662, 0.029547867999715382),
 (663, 0.08896512701337837),
 (664, 0.03480366832594501),
 (665, 0.21217447349500163),
 (666, 0.060902133253528015),
 (667, 0.15877683720748892),
 (668, 0.10083683467310324),
 (669, 0.10062073215996296),
 (670, 0.0),
 (671, 0.08009231955886248),
 (672, 0.08039977681052937),
 (673, 0.0692958928675237),
 (674, 0.11975699017041917),
 (675, 0.053289366596837015),
 (676, 0.10904837950404936),
 (677, 0.11004874666982181),
 (678, 0.0726397220282243),
 (679, 0.11161368475593524),
 (680, 0.07221075716046446),
 (681, 0.16318814435504306),
 (682, 0.06751114949037705),
 (683, 0.0940207402449168),
 (684, 0.09001800540180063),
 (685, 0.08833527748583461),
 (686, 0.07862431594647298),
 (687, 0.07644420708636893),
 (688, 0.05527899928227821),
 (689, 0.08745286171094284),
 (690, 0.21654966521101157),
 (691, 0.06456864180286606),
 (692, 0.10515252921688405),
 (693, 0.0510955285624849),
 (694, 0.09463727629519564),
 (695, 0.13920187724940272),
 (696, 0.1398460356054498),
 (697, 0.12222646627042816),
 (698, 0.0734993936325038),
 (699, 0.14918965000735265),
 (700, 0.19327731092436978),
 (701, 0.05124500385567423),

In [ ]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:11]

[(719, 0.4542613712118689),
 (10, 0.4372631476231092),
 (4610, 0.42916577490060215),
 (10023, 0.4184137043778615),
 (633, 0.40996003084539384),
 (11052, 0.39845138398826135),
 (611, 0.3977196492840078),
 (333, 0.38892223413129867),
 (922, 0.3828403515853951),
 (544, 0.3805472489613685)]

In [ ]:
new_animes.head()

,uid,title,combined
0,28891,Haikyuu!! Second Season,follow their particip at the inter-high the ka...
1,23273,Shigatsu wa Kimi no Uso,music accompani the path of the human metronom...
2,34599,Made in Abyss,the abyss—a gape chasm stretch down into the d...
3,5114,Fullmetal Alchemist: Brotherhood,"""in order for someth to be obtain someth of eq..."
4,31758,Kizumonogatari III: Reiketsu-hen,after help reviv the legendari vampir kiss-sho...

In [ ]:
# Check if any rows match the title before trying to access the index
if any(new_animes['title'] == 'The Apothecary Diaries'):
  index = new_animes[new_animes['title'] == 'The Apothecary Diaries'].index[0]
  print(index)  # Print or use the index as needed
else:
  print("Title not found in DataFrame.")

Title not found in DataFrame.

In [ ]:
# Check if any rows match the title before trying to access the index
if any(new_animes['title'] == 'Naruto'):  # Changed 'naruto' to 'Naruto'
    index = new_animes[new_animes['title'] == 'Naruto'].index[0]  # Changed 'naruto' to 'Naruto'
    print(index)  # Print or use the index as needed
else:
    print("Title not found in DataFrame.")

144

In [ ]:
# Check if any rows match the title before trying to access the index
if any(new_animes['title'] == 'Hanamonogatari'):  # Changed 'naruto' to 'Naruto'
    index = new_animes[new_animes['title'] == 'Hanamonogatari'].index[0]  # Changed 'naruto' to 'Naruto'
    print(index)  # Print or use the index as needed
else:
    print("Title not found in DataFrame.")

288

In [ ]:
def recommend(anime):
  index=new_animes[new_animes['title']==anime].index[0]
  distances=sorted(list(enumerate(similarity[index])),reverse=True,key=lambda x:x[1])    #enumerate generates indexes and identify similarity score

  for i in distances[1:11]:
    print(new_animes.iloc[i[0]].title)

In [ ]:
recommend('Naruto')

Tteodori Kkachi
Bao Lian Deng
Bakukyuu Hit! Crash B-Daman
Generation of Chaos
Araiguma Rascal
Kouchuu Ouja Mushiking: Mori no Tami no Densetsu
Uchouten Kazoku 2
Chichi to Ko
Shokugeki no Souma
Akachan to Boku

In [ ]:
recommend('Overlord')

Show By Rock!!
Noisy Birth
Kokuen
Juicy Jungle
Connected
Ai Uta: Since 2007
Hane
Eien
Bungaku Shounen no Yuuutsu
Kimi ni Sekai

In [ ]:
recommend('Fullmetal Alchemist: Brotherhood')

Fullmetal Alchemist
Fullmetal Alchemist: The Sacred Star of Milos
Fullmetal Alchemist: The Conqueror of Shamballa
Shuumatsu Nani Shitemasu ka? Isogashii Desu ka? Sukutte Moratte Ii Desu ka?
Loveless
Abenobashi Mahou☆Shoutengai
Tsukimonogatari
Suisei no Gargantia
Oniichan Zurui
Nejimaki Seirei Senki: Tenkyou no Alderamin

In [ ]:
recommend('Made in Abyss')

["Eden's Bowy",
 'Layton Kyouju to Eien no Utahime',
 'El Cazador de la Bruja',
 'UN-GO',
 'Uchuu Kaizoku Captain Herlock',
 'Kindaichi Shounen no Jikenbo: Kuromajutsu Satsujin Jiken-hen',
 'Kawaikereba Hentai demo Suki ni Natte Kuremasu ka?',
 'The Sky Crawlers',
 'Koutetsujou no Kabaneri',
 'Tokkou']

In [ ]:
import pickle

pickle.dump(new_animes,open('Alist.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))

In [ ]:
import shutil
shutil.make_archive("similarity", "zip", root_dir=".", base_dir="similarity.pkl")

'/content/similarity.zip'

In [ ]:
from google.colab import files
files.download("similarity.zip")

In [ ]:
files.download("Alist.pkl")